version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres              
      POSTGRES_DB: ptedatabase
    ports:
      - "5432:5432"
    volumes:
      - pte_db:/var/lib/postgresql/data

volumes:
  pte_db:
